version: '3.8'

services:
  flask-app:
    build:
      context: ./backend-wf
      dockerfile: Dockerfile
    image: your-flask-image-name
    ports:
      - "5000:5000"
    depends_on:
      - database
      - rabbitmq

  celery-worker:
    build:
      context: ./backend-wf
      dockerfile: Dockerfilecelery
    image: your-celery-image-name
    depends_on:
      - flask-app
      - database
      - rabbitmq

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: test_pam
      POSTGRES_PASSWORD: test_pam
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

      
volumes:
  postgres_data:
  # node_modules:
